---
- name: Setup WordPress + Nginx
  hosts: all
  remote_user: ap
  become: yes
  become_method: sudo
  roles:
    - role: common
      tags: common
    - role: mariadb
      tags: mariadb
    - role: nginx 
      tags: nginx
    - role: php-fpm
      tags: php-fpm
    - role: wordpress
      tags: wordpress
